spring.application.name=ticket-booking-system

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/finalproject
spring.datasource.username=postgres
spring.datasource.password=Ankit@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# Redis Configuration (Local Development)
spring.data.redis.host=redis-13900.c11.us-east-1-3.ec2.cloud.redislabs.com
spring.data.redis.port=13900
spring.data.redis.timeout=2000ms
spring.data.redis.password=wjdJzbvRK3C80zD5AE9Gj2MYIK4L01Qr

server.port=8080

logging.level.com.example.finalprojectspringboot=DEBUG
logging.level.org.springframework.data.redis=INFO
